name: rqrcode_core

on:
  push:
    branches:
    - master
    - release/*
  pull_request:
    branches:
    - master

jobs:
  build:
    name: Test Ruby ${{ matrix.ruby_version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ruby_version:
          - ruby-2.5
          - ruby-2.6
          - ruby-2.7
          - ruby-3.0
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Use Ruby ${{ matrix.ruby_version }}
      uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby_version }}
    - name: Gem install and test
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rake test
